"""empty message

Revision ID: 19c4ee64d6c1
Revises: 8eac4e377c74
Create Date: 2023-11-10 05:59:59.528439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19c4ee64d6c1'
down_revision = '8eac4e377c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookstore', schema=None) as batch_op:
        batch_op.alter_column('zip_code',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('state')
        batch_op.drop_column('town')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookstore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('town', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('state', mysql.VARCHAR(length=10), nullable=True))
        batch_op.alter_column('zip_code',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
