"""empty message

Revision ID: 5e24ec22a8ea
Revises: 19c4ee64d6c1
Create Date: 2023-11-10 06:00:08.370947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e24ec22a8ea'
down_revision = '19c4ee64d6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookstore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('town', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookstore', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('town')

    # ### end Alembic commands ###
