"""empty message

Revision ID: 7354bd8f7a82
Revises: 
Create Date: 2023-11-08 07:13:43.578469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7354bd8f7a82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('administrator_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('administrator_name', sa.String(length=50), nullable=True),
    sa.Column('pass_word', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('administrator_id')
    )
    op.create_table('bookstore',
    sa.Column('bookstore_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('street_number', sa.String(length=10), nullable=True),
    sa.Column('street_address', sa.String(length=30), nullable=True),
    sa.Column('town', sa.String(length=10), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('library_name', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('bookstore_id')
    )
    op.create_table('customer',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.String(length=50), nullable=True),
    sa.Column('pass_word', sa.String(length=50), nullable=True),
    sa.Column('street_number', sa.String(length=10), nullable=True),
    sa.Column('street_address', sa.String(length=30), nullable=True),
    sa.Column('town', sa.String(length=10), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('genre',
    sa.Column('genre_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('genre_name')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('publisher',
    sa.Column('publisher_name', sa.String(length=50), nullable=False),
    sa.Column('street_number', sa.String(length=10), nullable=True),
    sa.Column('street_address', sa.String(length=30), nullable=True),
    sa.Column('town', sa.String(length=10), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('publisher_name')
    )
    op.create_table('store_block',
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('block_number')
    )
    op.create_table('book',
    sa.Column('book_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_name', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('edition', sa.Integer(), nullable=False),
    sa.Column('descriptions', sa.Text(), nullable=True),
    sa.Column('img_link', sa.String(length=50), nullable=True),
    sa.Column('publisher_name', sa.String(length=50), nullable=True),
    sa.Column('total_in_stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publisher_name'], ['publisher.publisher_name'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('store_block_genre',
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('bookstore_id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('available_capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_number'], ['store_block.block_number'], ),
    sa.ForeignKeyConstraint(['bookstore_id'], ['bookstore.bookstore_id'], ),
    sa.ForeignKeyConstraint(['genre_name'], ['genre.genre_name'], ),
    sa.PrimaryKeyConstraint('block_number', 'bookstore_id', 'genre_name')
    )
    op.create_table('book_genre',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ),
    sa.ForeignKeyConstraint(['genre_name'], ['genre.genre_name'], ),
    sa.PrimaryKeyConstraint('book_id', 'genre_name')
    )
    op.create_table('book_publisher_store',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('publisher_name', sa.String(length=50), nullable=False),
    sa.Column('bookstore_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ),
    sa.ForeignKeyConstraint(['bookstore_id'], ['bookstore.bookstore_id'], ),
    sa.ForeignKeyConstraint(['publisher_name'], ['publisher.publisher_name'], ),
    sa.PrimaryKeyConstraint('book_id', 'publisher_name', 'bookstore_id')
    )
    op.create_table('customer_order_book',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'order_id', 'book_id')
    )
    op.create_table('store_block_book',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('bookstore_id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_number'], ['store_block.block_number'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ),
    sa.ForeignKeyConstraint(['bookstore_id'], ['bookstore.bookstore_id'], ),
    sa.PrimaryKeyConstraint('book_id', 'block_number', 'bookstore_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_block_book')
    op.drop_table('customer_order_book')
    op.drop_table('book_publisher_store')
    op.drop_table('book_genre')
    op.drop_table('store_block_genre')
    op.drop_table('book')
    op.drop_table('store_block')
    op.drop_table('publisher')
    op.drop_table('orders')
    op.drop_table('genre')
    op.drop_table('customer')
    op.drop_table('bookstore')
    op.drop_table('administrator')
    # ### end Alembic commands ###
