"""empty message

Revision ID: d094700a6724
Revises: 5e24ec22a8ea
Create Date: 2023-11-11 12:27:16.981304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd094700a6724'
down_revision = '5e24ec22a8ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('administrator')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    op.create_table('administrator',
    sa.Column('administrator_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('administrator_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('pass_word', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('administrator_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
